FROM node:{{nodeVersion}}
RUN mkdir -p {{deployPath}}
WORKDIR {{deployPath}}
ARG NPM_TOKEN
COPY .npmrc .npmrc
{{#each files}}
COPY {{.}} {{../deployPath}}/{{.}}
{{/each}}
RUN npm install --unsafe-perm
CMD [ "npm", "run", "{{startScript}}" ]
